name: chat_app
description: "This is chat app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # go_router
  go_router: ^14.0.2

  #freezed
  freezed_annotation: ^2.4.1

  #json
  json_annotation: ^4.9.0

  #firebase
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7

  #localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.15.8

  #apploader
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #riverpod
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

  #freezed
  freezed: ^2.5.2

  #json
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
