// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9I_kGtb5gBC8XOQU4pNc6x0-_C8aJXqs',
    appId: '1:660994472624:web:e17d38cdfd728e335f5975',
    messagingSenderId: '660994472624',
    projectId: 'chat-app-d5602',
    authDomain: 'chat-app-d5602.firebaseapp.com',
    storageBucket: 'chat-app-d5602.appspot.com',
    measurementId: 'G-R3NXQEF52R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFWzVbX91coc89ROZaO-HnKv8Os0okA0',
    appId: '1:660994472624:android:c14be36efb5b25ee5f5975',
    messagingSenderId: '660994472624',
    projectId: 'chat-app-d5602',
    storageBucket: 'chat-app-d5602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoHow5vm8quK6lmWhkemC0h314522iW_k',
    appId: '1:660994472624:ios:4b272ba7afb583265f5975',
    messagingSenderId: '660994472624',
    projectId: 'chat-app-d5602',
    storageBucket: 'chat-app-d5602.appspot.com',
    iosBundleId: 'com.newwave.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoHow5vm8quK6lmWhkemC0h314522iW_k',
    appId: '1:660994472624:ios:4b272ba7afb583265f5975',
    messagingSenderId: '660994472624',
    projectId: 'chat-app-d5602',
    storageBucket: 'chat-app-d5602.appspot.com',
    iosBundleId: 'com.newwave.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9I_kGtb5gBC8XOQU4pNc6x0-_C8aJXqs',
    appId: '1:660994472624:web:d8bdb5eed6ccd6555f5975',
    messagingSenderId: '660994472624',
    projectId: 'chat-app-d5602',
    authDomain: 'chat-app-d5602.firebaseapp.com',
    storageBucket: 'chat-app-d5602.appspot.com',
    measurementId: 'G-FX4N08Q2V3',
  );
}
